begin;

create table public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  user_name text not null,
  phone_number text,
  profile_image_path text,
  address_postcode text,
  address text,
  role text not null default 'passenger',
  current_latitude numeric,
  current_longitude numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_role_check
    check (role in ('passenger', 'driver'))
);

create table public.drivers (
  id integer generated by default as identity primary key,
  user_id uuid not null unique references public.users (id),
  driver_license_image_path text not null,
  created_at timestamptz not null default now()
);

create table public.cars (
  id integer generated by default as identity primary key,
  car_name text not null,
  car_number text not null unique,
  car_capacity integer not null,
  created_at timestamptz not null default now(),
  constraint cars_capacity_check
    check (car_capacity >= 2)
);

create table public.shifts (
  id integer generated by default as identity primary key,
  driver_id integer not null references public.drivers (id),
  car_id integer not null references public.cars (id),
  start_time timestamptz not null,
  end_time timestamptz not null,
  status text not null default 'available',
  earnings numeric,
  created_at timestamptz not null default now(),
  constraint shifts_time_order_check
    check (start_time < end_time),
  constraint shifts_status_check
    check (status in ('available', 'booked', 'completed', 'canceled')),
  constraint shifts_earnings_check
    check (earnings is null or earnings >= 0)
);

create table public.reservations (
  id integer generated by default as identity primary key,
  user_id uuid not null references public.users (id),
  shift_id integer references public.shifts (id),
  status text not null default 'pending',
  passenger_count integer not null,
  start_address text not null,
  start_latitude numeric not null,
  start_longitude numeric not null,
  end_address text not null,
  end_latitude numeric not null,
  end_longitude numeric not null,
  scheduled_pickup_at timestamptz not null,
  fare numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reservations_status_check
    check (status in ('pending', 'accepted', 'in_progress', 'completed', 'canceled')),
  constraint reservations_passenger_count_check
    check (passenger_count between 1 and 3),
  constraint reservations_fare_check
    check (fare is null or fare >= 0)
);

create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger users_set_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

create trigger reservations_set_updated_at
before update on public.reservations
for each row
execute function public.set_updated_at();

create function public.enforce_shift_constraints()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  conflicting_shift_id integer;
begin
  if tg_op = 'UPDATE' then
    perform pg_catalog.pg_advisory_xact_lock(1, least(old.driver_id, new.driver_id));
    if old.driver_id <> new.driver_id then
      perform pg_catalog.pg_advisory_xact_lock(1, greatest(old.driver_id, new.driver_id));
    end if;

    perform pg_catalog.pg_advisory_xact_lock(2, least(old.car_id, new.car_id));
    if old.car_id <> new.car_id then
      perform pg_catalog.pg_advisory_xact_lock(2, greatest(old.car_id, new.car_id));
    end if;
  else
    perform pg_catalog.pg_advisory_xact_lock(1, new.driver_id);
    perform pg_catalog.pg_advisory_xact_lock(2, new.car_id);
  end if;

  if tg_op = 'UPDATE'
    and old.status = 'canceled'
    and new.status <> 'canceled'
  then
    raise exception 'A canceled shift cannot be reactivated'
      using errcode = '23514';
  end if;

  if tg_op = 'UPDATE'
    and old.status <> 'canceled'
    and new.status = 'canceled'
  then
    perform 1
    from public.reservations
    where shift_id = old.id
      and status in ('accepted', 'in_progress')
    for update;

    if exists (
      select 1
      from public.reservations
      where shift_id = old.id
        and status = 'in_progress'
    ) then
      raise exception 'A shift with an in-progress reservation cannot be canceled'
        using errcode = '23514';
    end if;
  end if;

  if new.status <> 'canceled' then
    select shifts.id
    into conflicting_shift_id
    from public.shifts as shifts
    where shifts.id <> new.id
      and shifts.status <> 'canceled'
      and (shifts.driver_id = new.driver_id or shifts.car_id = new.car_id)
      and shifts.start_time < new.end_time
      and new.start_time < shifts.end_time
    limit 1;

    if conflicting_shift_id is not null then
      raise exception 'Shift overlaps with active shift %', conflicting_shift_id
        using errcode = '23P01';
    end if;
  end if;

  return new;
end;
$$;

create trigger shifts_enforce_constraints
before insert or update on public.shifts
for each row
execute function public.enforce_shift_constraints();

create function public.rematch_reservations_after_shift_cancellation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.status <> 'canceled' and new.status = 'canceled' then
    update public.reservations
    set status = 'pending', shift_id = null
    where shift_id = new.id
      and status = 'accepted';
  end if;

  return new;
end;
$$;

create trigger shifts_rematch_after_cancellation
after update of status on public.shifts
for each row
execute function public.rematch_reservations_after_shift_cancellation();

create index shifts_driver_id_idx
  on public.shifts (driver_id);

create index shifts_car_id_idx
  on public.shifts (car_id);

create index shifts_matching_idx
  on public.shifts (status, start_time, end_time);

create index reservations_user_id_idx
  on public.reservations (user_id);

create index reservations_shift_status_idx
  on public.reservations (shift_id, status);

create index reservations_rematching_idx
  on public.reservations (status, scheduled_pickup_at);

alter table public.users enable row level security;
alter table public.drivers enable row level security;
alter table public.cars enable row level security;
alter table public.shifts enable row level security;
alter table public.reservations enable row level security;

revoke all privileges on table public.users from public, anon, authenticated;
revoke all privileges on table public.drivers from public, anon, authenticated;
revoke all privileges on table public.cars from public, anon, authenticated;
revoke all privileges on table public.shifts from public, anon, authenticated;
revoke all privileges on table public.reservations from public, anon, authenticated;

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.users to service_role;
grant select, insert, update, delete on table public.drivers to service_role;
grant select, insert, update, delete on table public.cars to service_role;
grant select, insert, update, delete on table public.shifts to service_role;
grant select, insert, update, delete on table public.reservations to service_role;

revoke all privileges on sequence public.drivers_id_seq from public, anon, authenticated;
revoke all privileges on sequence public.cars_id_seq from public, anon, authenticated;
revoke all privileges on sequence public.shifts_id_seq from public, anon, authenticated;
revoke all privileges on sequence public.reservations_id_seq from public, anon, authenticated;

grant usage, select on sequence public.drivers_id_seq to service_role;
grant usage, select on sequence public.cars_id_seq to service_role;
grant usage, select on sequence public.shifts_id_seq to service_role;
grant usage, select on sequence public.reservations_id_seq to service_role;

revoke execute on function public.set_updated_at() from public, anon, authenticated;
revoke execute on function public.enforce_shift_constraints() from public, anon, authenticated;
revoke execute on function public.rematch_reservations_after_shift_cancellation() from public, anon, authenticated;

commit;
